package sample.results.test.multiple.bitrise.com.multipletestresultssample;

import org.junit.Test;

import static org.junit.Assert.*;

/**
 * Example local unit test, which will execute on the development machine (host).
 *
 * @see <a href="http://d.android.com/tools/testing">Testing documentation</a>
 */
public class UnitTest0 {
    @Test
    public void correctCase0() throws Exception {
        assertEquals(4, 2 + 2);
    }
    @Test
    public void correctCase1() throws Exception {
        assertEquals(4, 2 + 2);
    }
    @Test
    public void correctCase2() throws Exception {
        assertEquals(4, 2 + 2);
    }
    @Test
    public void correctCase3() throws Exception {
        assertEquals(4, 2 + 2);
    }
    @Test
    public void correctCase4() throws Exception {
        assertEquals(4, 2 + 2);
    }
    @Test
    public void correctCase5() throws Exception {
        assertEquals(4, 2 + 2);
    }
    @Test
    public void correctCase6() throws Exception {
        assertEquals(4, 2 + 2);
    }
    @Test
    public void correctCase7() throws Exception {
        assertEquals(4, 2 + 2);
    }
    @Test
    public void correctCase8() throws Exception {
        assertEquals(4, 2 + 2);
    }
    @Test
    public void correctCase9() throws Exception {
        assertEquals(4, 2 + 2);
    }
    @Test
    public void failingCase0() throws Exception {
        assertEquals(4, 2 + 1);
    }
    @Test
    public void failingCase1() throws Exception {
        assertEquals(4, 2 + 1);
    }
    @Test
    public void failingCase2() throws Exception {
        assertEquals(4, 2 + 1);
    }
    @Test
    public void failingCase3() throws Exception {
        assertEquals(4, 2 + 1);
    }
    @Test
    public void failingCase4() throws Exception {
        assertEquals(4, 2 + 1);
    }
    @Test
    public void failingCase5() throws Exception {
        assertEquals(4, 2 + 1);
    }
    @Test
    public void failingCase6() throws Exception {
        assertEquals(4, 2 + 1);
    }
    @Test
    public void failingCase7() throws Exception {
        assertEquals(4, 2 + 1);
    }
    @Test
    public void failingCase8() throws Exception {
        assertEquals(4, 2 + 1);
    }
    @Test
    public void failingCase9() throws Exception {
        assertEquals(4, 2 + 1);
    }
}